layout_spectrum: 0.5515945330262184
typography_spectrum: 0.22562537994235754
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1254773724358529
  lightness: 0.8064457955770195
  saturation: 0.1544091796968132
  rhythmicContrast: 0.6434325140435249
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Test001
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Main site
    url: 'http://stocksfamily.org'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Grid Test 001
description: Does it work yet?
purpose: []
