name: Test001
favicon: null
layout_spectrum: 0.88662
typography_spectrum: 0.135943547822535
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Grid Test 001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1254773724358529
  lightness: 0.8064457955770195
  saturation: 0.1544091796968132
  rhythmicContrast: 0.6434325140435249
purpose: []
